
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: compliance-operator
  template:
    metadata:
      labels:
        name: compliance-operator
      annotations:
        workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    spec:
      serviceAccountName: compliance-operator
      containers:
        - name: compliance-operator
          image: compliance-operator
          command:
            - compliance-operator
            - operator
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              memory: "20Mi"
              cpu: "10m"
            limits:
              memory: "500Mi"
              cpu: "200m"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RELATED_IMAGE_OPENSCAP
              # Hardcoding this temporarily until its propagated to CI
              value: "ghcr.io/complianceascode/openscap-ocp:latest"
            - name: RELATED_IMAGE_OPERATOR
              value: "ghcr.io/complianceascode/compliance-operator:latest"
            - name: RELATED_IMAGE_PROFILE
              value: "ghcr.io/complianceascode/k8scontent:latest"
          volumeMounts:
            - name: serving-cert
              mountPath: /var/run/secrets/serving-cert
              readOnly: true
      volumes:
        - name: serving-cert
          secret:
            secretName: compliance-operator-serving-cert
            optional: true
