FROM registry.redhat.io/ubi9/ubi-minimal:latest

# Test
LABEL \
        io.k8s.display-name="must-gather cli for compliance-operator" \
        io.k8s.description="An must-gather cli for the compliance-operator." \
        io.openshift.tags="openshift,compliance,security" \
        com.redhat.delivery.appregistry="false" \
        summary="A must-gather cli for compliance-operator" \
        description="An image to collect debug information from compliance-operator" \
        maintainer="Red Hat ISC <isc-team@redhat.com>" \
        License="GPLv2+" \
        name="openshift-compliance-must-gather" \
        com.redhat.component="openshift-compliance-must-gather-container" \
        io.openshift.maintainer.product="OpenShift Container Platform" \
        io.openshift.maintainer.component="Compliance Operator" \
        version=1.7.1

# Install openshift-clients, jq, tar, and rsync, which are required for
# must-gather.
RUN microdnf -y install openshift-clients jq tar rsync

WORKDIR /go/src/github.com/ComplianceAsCode/compliance-operator

COPY ./LICENSE /licenses/LICENSE
COPY ./utils/must-gather/gather* /usr/bin/
COPY ./utils/must-gather/fetch-raw-results-pod-template.yaml /usr/share/

ENTRYPOINT /usr/bin/gather
